### ISSUE TITLE
Adding link to external video

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/xcube#2]
## Lets call them PLUGS

On site it will look like  **Title + Thumb** which will have **link** to some external sites.

Its simple 4 fields we need for this:
- [x] title
- [x] thumbnail 
- [x] url 
- [x] category

**Comment by shtefcs** [comment]
@edionmelarosa This is how it should looks like creating _Plug_ http://screencast.com/t/fQI5haRglDF3

It's similar to adding video, just have fewer fields.

**Comment by edionmelarosa** [comment]
Have pushed updates for this.

**Comment by shtefcs** [comment]
okay, will check it out.
