### ISSUE TITLE
List of fixes #1

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/xcube#3]
## Here is list of things that need to be edited, fixed.
- [x] **Title** of video page should be just a **Title**. Right now its automatically add `theme for`  `category name`. Remove that, and leave only Title.
- [x] Remove `category name` from url and replace it with `/p/`. Right now url is `http://localhost:3000/teen/mature-italian-mom` but, changed it to be `http://localhost:3000/p/mature-italian-mom`
- [x] Allow to manually add video url into `Vid file url` field. For example if i want to add this video `http://vt.tumblr.com/tumblr_mfm91z9z2B1rp7ded.mp4`
- [x] Display latest added video, as last on homepage. http://screencast.com/t/DD03xhJP
- [x] In admin change `themes` to `videos` http://screencast.com/t/bwgC40dRh
- [ ] SEO to be checked after deployed on server. Will ask @martin-mh today if he can do it.

**Comment by mhammerc** [comment]
yeah ! not today but i can work on it tomorrow on in two days ;)

**Comment by shtefcs** [comment]
oki Marty :)

**Comment by shtefcs** [comment]
@edionmelarosa  Some things are not fixed, and some are more screwed :D 
- [x] App is restarting/crashing itself http://screencast.com/t/xYJjt38vMk
- [x] Title is not fixed its say `girls need love video for undefined` and it should be only `girls need love`
- [x] description of video is missing on homepage and video page. On homepage it was limited to XX characters. Try to back that as it was before (themia.co)
- [x] When i come back from video page to homepage, there is no videos on homepage 
- [x] Videos are not sorted by latest on homepage.

**Comment by edionmelarosa** [comment]
@shtefcs  - Title is not fixed its say girls need love video for undefined and it should be only girls need love

<<< that is for the SEO part right? or is it on the video page? Can I see your view? Imean screenshot.

**Comment by edionmelarosa** [comment]
@martin-mh - Just need to ask where is the before.insert for collection is set (im getting already defined error when using it)? I need to update it to a collection hooks on videos collection for the created field(date when video is created) so, I won't need to set it on simpleSchema. For now I added it but it show on form. I have option also for hide but I can't find a way to do from simpleSchema settings. Sorry for long text :)

**Comment by shtefcs** [comment]
@edionmelarosa Description on video page should be full, not limited to XX characters, and it was below video player.

**Comment by shtefcs** [comment]
@edionmelarosa  The app is still restarting/crashing, not sure why http://screencast.com/t/bYiaYyRs5odv

**Comment by edionmelarosa** [comment]
@shtefcs  It's not showing on my local server. 

http://screencloud.net/v/k1YQ

**Comment by shtefcs** [comment]
Try to add some videos and let it run for some time.

**Comment by shtefcs** [comment]
http://screencast.com/t/YphqEciQ3z

**Comment by mhammerc** [comment]
Hi ! i'm sorry i do not have time to work on SEO for now

**Comment by shtefcs** [comment]
@martin-mh who asked you for seo ? :D

Oh, the last item. I meant, that i will check SEO and ask you to deploy only.

**Comment by shtefcs** [comment]
@edionmelarosa Edi, can u display plugs somewhere on site **Title + thumb *\* which will be linked with **url** and category as well.

Jelena will take care of the rest, just display them as videos on homepage.

**Comment by edionmelarosa** [comment]
@shtefcs Plugs Aleady added on home page
