### ISSUE TITLE
Bugs, fixes, list 2 for Marty

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/xcube#5]
- [x] Loading indicator instead of this http://screencast.com/t/6VhczodY
- [x] Fixing redirection of valid links to 404 
- [x] adding 301 redirection for all links from `www.` to none `www`
- [x] replacing Disqus code with new one (we have it now from themia.co)

```
<div id="disqus_thread"></div>
<script>
/**
* RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
* LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables
*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL; // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');

s.src = '//thesexcom.disqus.com/embed.js';

s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
```
- [x] Can you change this http://screencast.com/t/bgpuOu8nMl4E so it can be something easier to understand. Like to show a real date or something, so i can somehow order the videos.
- [x] Add a link to video page which will open in new tab http://screencast.com/t/Dlhh4JCftbX
- [x] Sitemap still have error http://the-sex.com/sitemap.xml
- [x] Google analytics not working. I added it in admin/seo as `UA-1200538-29` but not showing anything in stats.

**Comment by mhammerc** [comment]
The bug on sitemap came from the character '&'. I replaced it by the raw character '&amp;' (which is the same) and it's solved.

**Comment by mhammerc** [comment]
First task is done but it need testing !

**Comment by mhammerc** [comment]
pushing to the server

**Comment by mhammerc** [comment]
Okay, everything is now check ! Just one last remaining, i need to speak to you before check that

**Comment by shtefcs** [comment]
Good work Marty :+1: 

Two things noticed.
- Google bot render empty page http://screencast.com/t/D7dvGwJaG
- 404 page need to return 404 response, not 200 ok http://screencast.com/t/VOel9qbtei

**Comment by shtefcs** [comment]
One more quick fix.

I think you miss spelled this tag in sitemap `<video:content_loc>` . Instead you putted `<video:loc>` which google detect as error .

![](http://content.screencast.com/users/shtefcs/folders/Jing/media/c1f3bbac-238e-4576-b4ab-c416469b1535/2016-02-11_0411.png)

**Comment by shtefcs** [comment]
Title/description is not working on homepage.

In `admin/dictionary` I putted the Title & Description, but it didn't change.

http://screencast.com/t/k1DRmimltt4

Also, please remove this text `Vanila.io Ghost Themes`

**Comment by shtefcs** [comment]
- [ ] Google bot render empty page http://screencast.com/t/D7dvGwJaG
- [x] 404 page need to return 404 response, not 200 ok http://screencast.com/t/VOel9qbtei
- [x] Sitemap fix. It should be video:content_loc not video:loc
- [x] Title/description is not working on homepage.
- [x] Please remove this text Vanila.io Ghost Themes

**Comment by mhammerc** [comment]
Have to test for 404 pages
